
insert into dap_dapsystem (APPSCOPE, DEF1, DEF2, DEF3, DEVMODULE, DR, ISACCOUNT, ISITEM, ISNCINNERMODULE, ISRELATEDEV, MODULEID, NODEORDER, ORGTYPECODE, PARENTCODE, PRODUCTSCOPE, RESID, SUPPORTCLOSEACCBOOK, SYSTYPECODE, SYSTYPENAME, TS)
values (1, null, null, null, 'fee', 0, 'Y', 'N', 'Y', null, 'FEH1', null, 'GLOBLE00000000000000', 'FE', null, null, 'N', 'FEH1', '人工费用计算', '2017-11-18 23:40:24');

insert into dap_dapsystem (APPSCOPE, DEF1, DEF2, DEF3, DEVMODULE, DR, ISACCOUNT, ISITEM, ISNCINNERMODULE, ISRELATEDEV, MODULEID, NODEORDER, ORGTYPECODE, PARENTCODE, PRODUCTSCOPE, RESID, SUPPORTCLOSEACCBOOK, SYSTYPECODE, SYSTYPENAME, TS)
values (1, null, null, null, 'fee', 0, 'N', 'N', 'Y', null, 'FE', null, 'GLOBLE00000000000000', '~', null, null, 'N', 'FEE', '费用计算', '2017-11-18 23:34:37');

