
insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('subagreement', 'SYSTEM', '~', null, 0, null, 0, 'fee.subagreement', null, 'FEH1', 'FEH10201', null, '0001ZZ10000000008M82', 'FEH10201', '@@@@', null, null, null, '2017-11-26 19:00:43', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('其他收合同至人工工资审批', 'SYSTEM', null, null, 0, null, 0, 'ct.ct_ar', null, 'FEH1', '40203004', null, '1001ZZ10000000001BWL', 'FE03REFZ5', '@@@@', null, null, 'N', '2017-11-26 16:53:38', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('其他收合同至人工工资审批（单表）', 'SYSTEM', null, null, 0, null, 0, 'ct.ct_ar', null, 'FEH1', '40203004', null, '1001ZZ10000000001BUU', 'FE03REFZ5V', '@@@@', null, null, 'N', '2017-11-26 16:53:07', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('withholding', 'SYSTEM', '~', null, 0, null, 0, 'fee.withholding', null, 'FEH1', 'FEH10202', null, '0001ZZ10000000008TWK', 'FEH10202', '@@@@', null, null, null, '2017-11-26 01:29:41', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('其他收合同至人工分包协议（单表）', 'SYSTEM', null, null, 0, null, 0, 'ct.ct_ar', null, 'CT', '40203004', null, '1001ZZ10000000000K5P', 'FE01REFZ5V', '@@@@', null, null, 'N', '2017-11-22 14:38:19', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('其他收合同至人工分包协议', 'SYSTEM', null, null, 0, null, 0, 'ct.ct_ar', null, 'CT', '40203004', null, '1001ZZ10000000000K3Q', 'FE01REFZ5', '@@@@', null, null, 'N', '2017-11-22 14:34:59', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('workteam', 'SYSTEM', '~', null, 0, null, 0, 'fee.workteam', null, 'FEH1', 'FEH10101', null, '0001ZZ10000000008N7N', 'FEH10101', '@@@@', null, null, null, '2017-11-21 17:01:28', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DEVORG, DIVIDERPROPORTION, DR, FUNCCODE, LAYER, METADATACLASS, MODEL_TYPE, MODULECODE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, PK_ORG, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('wagesappro', 'SYSTEM', '~', null, 0, null, 0, 'fee.wagesappro', null, 'FEH1', 'FEH10203', null, '0001ZZ10000000008MS4', 'FEH10203', '@@@@', null, null, null, '2017-11-21 17:00:10', null);


