<?xml version="1.0" encoding="gbk"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
<bean id="billactionTotal" class="nc.pubapp.pade.platform.vo.BillactionTotal"><property name="actionList">
<list></list>
</property>
<property name="billtypecode" value="FE01"/>
<property name="pk_billtypeid" value="0001ZZ10000000008MKK"/>
</bean>

</beans>